compiler:
  solc:
    version: 0.8.7
networks:
    development:
        weth_address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
        busd_address: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
        usdt_address: "0x55d398326f99059ff775485246999027b3197955"
        usdc_address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
        pancakeswap_factory_address: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
        verify: False
    ganache-local:
        verify: False
    bsc-test:
        weth_address: "0x1e33833a035069f42d68D1F53b341643De1C018D"
        busd_address: "0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee"
        usdt_address: "0x337610d27c682E347C9cD60BD4b3b107C9d34dDd"
        usdc_address: "0x64544969ed7EBf5f083679233325356EbE738930"
        pancakeswap_factory_address: "0x6725F303b657a9451d8BA641348b6761A6CC7a17"
        verify: False
    bsc-main:
        weth_address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
        busd_address: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
        usdt_address: "0x55d398326f99059ff775485246999027b3197955"
        usdc_address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
        pancakeswap_factory_address: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
        verify: False    
    bsc-main-fork:
        weth_address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
        busd_address: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
        usdt_address: "0x55d398326f99059ff775485246999027b3197955"
        usdc_address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
        pancakeswap_factory_address: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
        verify: False
    polybit-bsc-fork:
        weth_address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
        busd_address: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
        usdt_address: "0x55d398326f99059ff775485246999027b3197955"
        usdc_address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
        pancakeswap_factory_address: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
        verify: False  
    polygon-test:
        verify: False
    polygon-main:
        verify: False
wallets:
    polybit_owner: ${POLYBIT_OWNER_ADDRESS}
    polybit_owner_key: ${POLYBIT_OWNER_PRIVATE_KEY}
    rebalancer_owner: ${REBALANCER_OWNER_ADDRESS}
    rebalancer_owner_key: ${REBALANCER_OWNER_PRIVATE_KEY}
    router_owner: ${ROUTER_OWNER_ADDRESS}
    router_owner_key: ${ROUTER_OWNER_PRIVATE_KEY}
    wallet_owner_key: ${WALLET_OWNER_PRIVATE_KEY}
    non_owner_key: ${NON_OWNER_PRIVATE_KEY}
    polybit_fee: ${POLYBIT_FEE_ADDRESS}
    test_polybit_owner: ${TEST_POLYBIT_OWNER_ADDRESS}
    test_polybit_owner_key: ${TEST_POLYBIT_OWNER_PRIVATE_KEY}
    test_rebalancer_owner: ${TEST_REBALANCER_OWNER_ADDRESS}
    test_rebalancer_owner_key: ${TEST_REBALANCER_OWNER_PRIVATE_KEY}
    test_router_owner: ${TEST_ROUTER_OWNER_ADDRESS}
    test_router_owner_key: ${TEST_ROUTER_OWNER_PRIVATE_KEY}
    test_wallet_owner_key: ${TEST_WALLET_OWNER_PRIVATE_KEY}
    test_non_owner_key: ${TEST_NON_OWNER_PRIVATE_KEY}
    test_polybit_fee: ${TEST_POLYBIT_FEE_ADDRESS}
    test_polybit_fee_key: ${TEST_POLYBIT_FEE_PRIVATE_KEY}
dotenv: .env
polybit-finance:
    version: 0.0.6
data_providers:
    coingecko: ${COINGECKO_API_KEY}
    moralis: ${MORALIS_API_KEY}