compiler:
  solc:
    version: 0.8.7
networks:
    development:
        weth_address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
        busd_address: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
        usdt_address: "0x55d398326f99059ff775485246999027b3197955"
        usdc_address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
        pancakeswap_factory_address: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
        verify: False
    ganache-local:
        verify: False
    bsc-test:
        weth_address: "0x652415C1E99FE1dD82b18C55C8Fe74B1EE933243"
        busd_address: "0xE3c966bc5529aD7219B49F69Ab01AC05d0E153F6"
        usdt_address: "0x3F0ab9b22e64645a1BEfA84f6B888C71A2798c94"
        usdc_address: "0xd533F685Ae10F7DD61eCC03fbe47358084b4E8ac"
        pancakeswap_factory_address: "0x5Ef9badaa090c5837427d16a5761CbFFDACF5Fa8"
        verify: False
    bsc-main:
        weth_address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
        busd_address: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
        usdt_address: "0x55d398326f99059ff775485246999027b3197955"
        usdc_address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
        pancakeswap_factory_address: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
        verify: False    
    bsc-main-fork:
        weth_address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
        busd_address: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
        usdt_address: "0x55d398326f99059ff775485246999027b3197955"
        usdc_address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
        pancakeswap_factory_address: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
        verify: False
    polybit-bsc-fork:
        weth_address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
        busd_address: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
        usdt_address: "0x55d398326f99059ff775485246999027b3197955"
        usdc_address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
        pancakeswap_factory_address: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
        verify: False  
    polygon-test:
        verify: False
    polygon-main:
        verify: False
wallets:
    polybit_owner: ${POLYBIT_OWNER_ADDRESS}
    polybit_owner_key: ${POLYBIT_OWNER_PRIVATE_KEY}
    rebalancer_owner: ${REBALANCER_OWNER_ADDRESS}
    rebalancer_owner_key: ${REBALANCER_OWNER_PRIVATE_KEY}
    router_owner: ${ROUTER_OWNER_ADDRESS}
    router_owner_key: ${ROUTER_OWNER_PRIVATE_KEY}
    wallet_owner_key: ${WALLET_OWNER_PRIVATE_KEY}
    non_owner_key: ${NON_OWNER_PRIVATE_KEY}
    polybit_fee: ${POLYBIT_FEE_ADDRESS}
    polybit_fee_key: ${POLYBIT_FEE_ADDRESS_PRIVATE_KEY}
    test_polybit_owner: ${TEST_POLYBIT_OWNER_ADDRESS}
    test_polybit_owner_key: ${TEST_POLYBIT_OWNER_PRIVATE_KEY}
    test_rebalancer_owner: ${TEST_REBALANCER_OWNER_ADDRESS}
    test_rebalancer_owner_key: ${TEST_REBALANCER_OWNER_PRIVATE_KEY}
    test_router_owner: ${TEST_ROUTER_OWNER_ADDRESS}
    test_router_owner_key: ${TEST_ROUTER_OWNER_PRIVATE_KEY}
    test_wallet_owner_key: ${TEST_WALLET_OWNER_PRIVATE_KEY}
    test_non_owner_key: ${TEST_NON_OWNER_PRIVATE_KEY}
    test_polybit_fee: ${TEST_POLYBIT_FEE_ADDRESS}
    test_polybit_fee_key: ${TEST_POLYBIT_FEE_PRIVATE_KEY}
dotenv: .env
polybit-finance:
    version: 0.0.6
data_providers:
    coingecko: ${COINGECKO_API_KEY}
    moralis: ${MORALIS_API_KEY}